spring:
  profiles:
    include:
      - core
      - rds
      - redis
jwt:
  secretKey: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest

logging:
  level: info
